import type { InventoryItem, Notification, User } from "./types";
import { PlaceHolderImages } from "./placeholder-images";

const userAvatar = PlaceHolderImages.find((img) => img.id === 'user-avatar');

export const user: User = {
    name: "Usuario Admin",
    email: "admin@inventoryedge.com",
    avatar: userAvatar?.imageUrl || "https://picsum.photos/seed/user-avatar/40/40",
};

export const inventoryItems: InventoryItem[] = [
  {
    id: "ITEM-001",
    name: "Ratón Inalámbrico",
    description: "Ratón inalámbrico ergonómico con conectividad de 2.4 GHz.",
    quantity: 50,
    location: "Almacén A, Estante 3",
    category: "Electronics",
    dateAdded: "2023-10-26T10:00:00Z",
    manufacturer: "LogiTech",
    status: "In Stock",
  },
  {
    id: "ITEM-002",
    name: "Silla de Oficina",
    description: "Silla de oficina ergonómica con soporte lumbar.",
    quantity: 5,
    location: "Sala de exposición",
    category: "Furniture",
    dateAdded: "2023-10-25T14:30:00Z",
    manufacturer: "Herman Miller",
    status: "Low Stock",
  },
  {
    id: "ITEM-003",
    name: "Paquete de Papel A4",
    description: "500 hojas de papel A4 de alta calidad.",
    quantity: 200,
    location: "Almacén B",
    category: "Office Supplies",
    dateAdded: "2023-10-24T09:00:00Z",
    manufacturer: "PaperFirst",
    status: "In Stock",
  },
  {
    id: "ITEM-004",
    name: "Licencia ProjectPro",
    description: "Licencia de 1 año para el software ProjectPro.",
    quantity: 0,
    location: "Bóveda Digital",
    category: "Software",
    dateAdded: "2023-10-23T11:00:00Z",
    manufacturer: "SoftWorks",
    status: "Out of Stock",
  },
  {
    id: "ITEM-005",
    name: "Teclado Mecánico",
    description: "Teclado mecánico RGB con interruptores azules.",
    quantity: 25,
    location: "Almacén A, Estante 4",
    category: "Electronics",
    dateAdded: "2023-10-22T16:00:00Z",
    manufacturer: "KeyChron",
    status: "In Stock",
  },
  {
    id: "ITEM-006",
    name: "Escritorio Elevable",
    description: "Escritorio de altura ajustable.",
    quantity: 10,
    location: "Almacén B, Sección 1",
    category: "Furniture",
    dateAdded: "2023-10-21T13:20:00Z",
    manufacturer: "Uplift Desk",
    status: "In Stock",
  },
  {
    id: "ITEM-007",
    name: "Paquete de Notas Adhesivas",
    description: "Paquete de 12 blocs de notas adhesivas de colores.",
    quantity: 3,
    location: "Almacén A",
    category: "Office Supplies",
    dateAdded: "2023-10-20T10:15:00Z",
    manufacturer: "3M",
    status: "Low Stock",
  },
  {
    id: "ITEM-008",
    name: "Licencia DesignSuite",
    description: "Suite completa alternativa a Adobe Creative Cloud.",
    quantity: 15,
    location: "Bóveda Digital",
    category: "Software",
    dateAdded: "2023-10-19T18:00:00Z",
    manufacturer: "Affinity",
    status: "In Stock",
  },
  {
    id: "ITEM-009",
    name: "Monitor 4K",
    description: "Monitor UHD 4K de 27 pulgadas.",
    quantity: 8,
    location: "Almacén A, Estante 1",
    category: "Electronics",
    dateAdded: "2023-10-18T12:00:00Z",
    manufacturer: "Dell",
    status: "Low Stock",
  },
  {
    id: "ITEM-010",
    name: "Pizarra Blanca",
    description: "Pizarra blanca magnética grande de 4x6 pies.",
    quantity: 0,
    location: "Almacén C",
    category: "Furniture",
    dateAdded: "2023-10-17T15:45:00Z",
    manufacturer: "BoardMaster",
    status: "Out of Stock",
  },
];

export const notifications: Notification[] = [
    {
        id: "NOTIF-001",
        title: "Alerta de Stock Bajo",
        description: "El artículo 'Silla de Oficina' (ITEM-002) tiene poco stock.",
        read: false,
        createdAt: "2023-10-28T10:00:00Z",
    },
    {
        id: "NOTIF-002",
        title: "Agotado",
        description: "El artículo 'Licencia ProjectPro' (ITEM-004) está agotado.",
        read: false,
        createdAt: "2023-10-27T14:30:00Z",
    },
    {
        id: "NOTIF-003",
        title: "Producto a punto de expirar",
        description: "El artículo 'Barritas energéticas' (ITEM-011) expirará en 7 días.",
        read: true,
        createdAt: "2023-10-26T09:00:00Z",
    },
];
