import type { InventoryItem, Notification, User } from "./types";
import { PlaceHolderImages } from "./placeholder-images";

const userAvatar = PlaceHolderImages.find((img) => img.id === 'user-avatar');

export const user: User = {
    name: "Admin User",
    email: "admin@inventoryedge.com",
    avatar: userAvatar?.imageUrl || "https://picsum.photos/seed/user-avatar/40/40",
};

export const inventoryItems: InventoryItem[] = [
  {
    id: "ITEM-001",
    name: "Wireless Mouse",
    description: "Ergonomic wireless mouse with 2.4 GHz connectivity.",
    quantity: 50,
    location: "Warehouse A, Shelf 3",
    category: "Electronics",
    dateAdded: "2023-10-26T10:00:00Z",
    manufacturer: "LogiTech",
    status: "In Stock",
  },
  {
    id: "ITEM-002",
    name: "Office Chair",
    description: "Ergonomic office chair with lumbar support.",
    quantity: 5,
    location: "Showroom",
    category: "Furniture",
    dateAdded: "2023-10-25T14:30:00Z",
    manufacturer: "Herman Miller",
    status: "Low Stock",
  },
  {
    id: "ITEM-003",
    name: "A4 Paper Ream",
    description: "500 sheets of high-quality A4 paper.",
    quantity: 200,
    location: "Storage Room B",
    category: "Office Supplies",
    dateAdded: "2023-10-24T09:00:00Z",
    manufacturer: "PaperFirst",
    status: "In Stock",
  },
  {
    id: "ITEM-004",
    name: "ProjectPro License",
    description: "1-year license for ProjectPro software.",
    quantity: 0,
    location: "Digital Vault",
    category: "Software",
    dateAdded: "2023-10-23T11:00:00Z",
    manufacturer: "SoftWorks",
    status: "Out of Stock",
  },
  {
    id: "ITEM-005",
    name: "Mechanical Keyboard",
    description: "RGB mechanical keyboard with blue switches.",
    quantity: 25,
    location: "Warehouse A, Shelf 4",
    category: "Electronics",
    dateAdded: "2023-10-22T16:00:00Z",
    manufacturer: "KeyChron",
    status: "In Stock",
  },
  {
    id: "ITEM-006",
    name: "Standing Desk",
    description: "Adjustable height standing desk.",
    quantity: 10,
    location: "Warehouse B, Section 1",
    category: "Furniture",
    dateAdded: "2023-10-21T13:20:00Z",
    manufacturer: "Uplift Desk",
    status: "In Stock",
  },
  {
    id: "ITEM-007",
    name: "Sticky Notes Pack",
    description: "Pack of 12 colorful sticky note pads.",
    quantity: 3,
    location: "Storage Room A",
    category: "Office Supplies",
    dateAdded: "2023-10-20T10:15:00Z",
    manufacturer: "3M",
    status: "Low Stock",
  },
  {
    id: "ITEM-008",
    name: "DesignSuite License",
    description: "Full Adobe Creative Cloud alternative suite.",
    quantity: 15,
    location: "Digital Vault",
    category: "Software",
    dateAdded: "2023-10-19T18:00:00Z",
    manufacturer: "Affinity",
    status: "In Stock",
  },
  {
    id: "ITEM-009",
    name: "4K Monitor",
    description: "27-inch 4K UHD monitor.",
    quantity: 8,
    location: "Warehouse A, Shelf 1",
    category: "Electronics",
    dateAdded: "2023-10-18T12:00:00Z",
    manufacturer: "Dell",
    status: "Low Stock",
  },
  {
    id: "ITEM-010",
    name: "Whiteboard",
    description: "Large 4x6 ft magnetic whiteboard.",
    quantity: 0,
    location: "Storage Room C",
    category: "Furniture",
    dateAdded: "2023-10-17T15:45:00Z",
    manufacturer: "BoardMaster",
    status: "Out of Stock",
  },
];

export const notifications: Notification[] = [
    {
        id: "NOTIF-001",
        title: "Low Stock Alert",
        description: "Item 'Office Chair' (ITEM-002) is low on stock.",
        read: false,
        createdAt: "2023-10-28T10:00:00Z",
    },
    {
        id: "NOTIF-002",
        title: "Out of Stock",
        description: "Item 'ProjectPro License' (ITEM-004) is now out of stock.",
        read: false,
        createdAt: "2023-10-27T14:30:00Z",
    },
    {
        id: "NOTIF-003",
        title: "Product Expiring Soon",
        description: "Item 'Snack Bars' (ITEM-011) will expire in 7 days.",
        read: true,
        createdAt: "2023-10-26T09:00:00Z",
    },
];
