/** @type {import('next').NextConfig} */
const fs = require('fs');
const path = require('path');
const webpack = require('webpack');

const forceStandalone = process.env.NEXT_OUTPUT === 'standalone' || process.env.NEXT_STANDALONE === 'true';

// amplify_outputs.json is generated by `ampx pipeline-deploy` in CI and is gitignored.
// When it does not exist (local/codespace), we redirect webpack to a stub so the
// static import in amplify-config.ts resolves and the browser bundle loads without crashing.
const amplifyOutputsExists = fs.existsSync(path.join(__dirname, 'amplify_outputs.json'));
const amplifyOutputsStub = path.join(__dirname, 'amplify_outputs_stub.json');

const nextConfig = {
  /* config options here */
  // NOTE: Some hosting providers (incl. Amplify depending on the runtime mode)
  // can be sensitive to `output: 'standalone'`. Keep it opt-in.
  output: forceStandalone ? 'standalone' : undefined,
  typescript: {
    ignoreBuildErrors: true,
  },
  eslint: {
    ignoreDuringBuilds: true,
  },
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'placehold.co',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'picsum.photos',
        port: '',
        pathname: '/**',
      },
    ],
  },

  // This moves the Next.js build indicator to the bottom right
  // to avoid overlapping with the Firebase Studio UI.
  devIndicators: {
    buildActivityPosition: 'bottom-right',
  },
};

nextConfig.webpack = function (config) {
  if (!amplifyOutputsExists) {
    config.plugins.push(
      new webpack.NormalModuleReplacementPlugin(
        /amplify_outputs\.json$/,
        amplifyOutputsStub
      )
    );
  }
  return config;
};

module.exports = nextConfig;
